### ISSUE TITLE
localhost saving

### ISSUE THREAD

**Issue by coderinblack08** [Ashwagandhae/debate-flow#4]
would be nice if when I reload the website on accident i don't just lose all my stuff mid round lol.

If y'all want I can help cook up a PR.

**Comment by Ashwagandhae** [comment]
That's a good idea, much better than relying on "changes you made may not be saved", thank you! I think it's more complicated than just saving the flow in localStorage and loading it, though—right now doing that would make creating a new blank flow impossible. 

One possible solution: just list recently created flows in the tutorial area (there's a lot of empty space), and load them on click, but continue with the blank flow if you don't click. 

What do you think?

**Comment by Ashwagandhae** [comment]
I added it, let me know if you think it looks good :)

**Comment by coderinblack08** [comment]
yup looks great, maybe add a restore all flows button so if you accidentally close a tab, you can open up like all ur case and off-cases in one button.

**Comment by Ashwagandhae** [comment]
Clicking "open" already restores all of the flows that you had open (where flow = on case/off case sheet), each line is a separate group of flows from a separate session. So if in one debate I have flows Advantage 1, Advantage 2, Counterplan 1, it would look like this:
```
Advantage 1 | Advantage 2 | Counterplan ______________ 6:59 pm | open | ...
```
And if I open another tab for another debate with Advantage 1, K 1, the whole thing looks like this:
```
Advantage 1 | K 1 | __________________________________ 7:59 pm | open | ...
Advantage 1 | Advantage 2 | Counterplan ______________ 6:59 pm | open | ...
```

I'm glad you brought this up though because it might be confusing, usually you would have singular document titles for each. Do you think there's a way to make it clearer that each line represents a _group_ of flows?
